language: cpp

script:
    - cd GameOfLife
    - qmake -v
    - qmake -o Makefile GameOfLife.pro
    - make
    - cd ../Tester
    - qmake -v
    - qmake -o Makefile TesterForGameOfLife.pro
    - make
    - ./TesterForGameOfLife