language: cpp

compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - echo $CXX
    - g++ --version

script:
    - cd GameOfLife
    - qmake -v
    - qmake -o Makefile GameOfLife.pro
    - cat Makefile
    - make
    - cd ../Tester
    - qmake -v
    - qmake -o Makefile TesterForGameOfLife.pro
    - make
    - cat Makefile
    - ./TesterForGameOfLife