language: cpp

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
    - cd GameOfLife
    - qmake -v
    - qmake -o Makefile GameOfLife.pro
    - make
    - cd ../Tester
    - qmake -v
    - qmake -o Makefile TesterForGameOfLife.pro
    - make
    - ./TesterForGameOfLife