#ifndef DISPLAYGAMEBOARDONTHECOMMANDLINE_H
#define DISPLAYGAMEBOARDONTHECOMMANDLINE_H


class DisplayGameBoardOnTheCommandLine
{
public:
    DisplayGameBoardOnTheCommandLine();
};

#endif // DISPLAYGAMEBOARDONTHECOMMANDLINE_H